### ISSUE TITLE
Failed to create directory '/home/user/.local'

### ISSUE THREAD

**Issue by Koennn** [PSNRigner/discord-rpc-java#17]
When running `discordRpc.init()` the following exception is thrown
```
Exception in thread "main" java.lang.RuntimeException: Failed to create directory '/home/koenn/.local'
	at com.github.psnrigner.discordrpcjava.impl.BaseConnectionUnix.register(BaseConnectionUnix.java:188)
	at com.github.psnrigner.discordrpcjava.DiscordRpc.register(DiscordRpc.java:294)
	at com.github.psnrigner.discordrpcjava.DiscordRpc.init(DiscordRpc.java:130)
```

The directory `/home/koenn/.local` already exists, so it does not have to be created.

**Comment by Rigner** [comment]
Thank you for the issue, it means that the lib wasn't able to find the right user name.
I'll look into it.
