### ISSUE TITLE
NullPointerException Error

### ISSUE THREAD

**Issue by Cubxity** [PSNRigner/discord-rpc-java#9]
java.lang.NullPointerException: Initializing game
	at com.google.gson.JsonPrimitive.isPrimitiveOrString(JsonPrimitive.java:278)
	at com.google.gson.JsonPrimitive.setValue(JsonPrimitive.java:100)
	at com.google.gson.JsonPrimitive.<init>(JsonPrimitive.java:65)
	at com.github.psnrigner.DiscordRichPresence.toJson(DiscordRichPresence.java:364)
	at com.github.psnrigner.DiscordRpc.updatePresence(DiscordRpc.java:201)
	at me.cubxity.mods.minecord.Minecord.updatePresence(Minecord.java:67)
	at me.cubxity.mods.minecord.PresenceManager.update(PresenceManager.java:73)
	at me.cubxity.mods.minecord.Minecord.postInit(Minecord.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by PSNRigner** [comment]
That is because you didn't set status / details in rich presence request. I'll fix the code to default it to empty string.

**Comment by VRCube** [comment]
K, when you fixed it tell me 👍

**Comment by VRCube** [comment]
@PSNRigner Do you have discord? If you do, mind adding me :) ?

**Comment by PSNRigner** [comment]
My Discord is on my Github profile, my invites are opened

**Comment by VRCube** [comment]
@PSNRigner did you publish the new release on gradle?

**Comment by PSNRigner** [comment]
It is currently uploading
